"""empty message

Revision ID: 1f894ae15a90
Revises: a24be1bd5369
Create Date: 2025-10-22 14:57:32.397509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f894ae15a90'
down_revision = 'a24be1bd5369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_criacao', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_envio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_envio', sa.DATETIME(), nullable=True))
        batch_op.drop_column('data_criacao')

    # ### end Alembic commands ###
