"""empty message

Revision ID: 549e464c0881
Revises: 8785316d8ee0
Create Date: 2025-10-27 16:48:32.364506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549e464c0881'
down_revision = '8785316d8ee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
